---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "AFCMS"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    assignees:
      - "AFCMS"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "AFCMS"
