---
name: Go

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Install NodeJS Dependencies
        run: |
          cd frontend
          npm install --include=dev

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Build Go (Linux AMD64)
        run: |
          env GOOS=linux GOARCH=amd64 go build -o zoom-link-server -v ./...
      
      - name: Build Go (RasberryPi ARM)
        run: |
          env GOOS=linux GOARCH=arm GOARM=5 go build -o zoom-link-server-arm -v ./...