---
name: Go

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Install NodeJS Dependencies
        run: |
          cd frontend
          npm install --include=dev

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Build Go (Linux AMD64)
        run: |
          env GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -o zoom-link-server-amd64 -v ./...

      - name: Upload Build Files (Linux AMD64)
        uses: actions/upload-artifact@v3
        with:
          name: zoom-link-server-linux-amd64
          path: |
            frontend/build
            zoom-link-server-amd64

      - name: Install Build Dependencies (RasberryPi ARM)
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabi

      - name: Build Go (RasberryPi ARM)
        run: |
          env GOOS=linux GOARCH=arm GOARM=5 CGO_ENABLED=1 CC=arm-linux-gnueabi-gcc go build -o zoom-link-server-arm -v ./...

      - name: Upload Build Files (RasberryPi ARM)
        uses: actions/upload-artifact@v3
        with:
          name: zoom-link-server-linux-arm
          path: |
            frontend/build
            zoom-link-server-arm
